# Generated by Django 2.2.9 on 2019-12-31 16:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('nombre', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('fecha_fundacion', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('estilo', models.CharField(blank=True, max_length=30)),
                ('lugar_fundacion', models.CharField(blank=True, max_length=40)),
                ('ciudad', models.CharField(blank=True, max_length=50)),
                ('pais', models.CharField(blank=True, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('dni', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30)),
                ('apellidos', models.CharField(blank=True, max_length=60)),
                ('fecha_nacimiento', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('instrumento_principal', models.CharField(blank=True, max_length=20)),
                ('ciudad', models.CharField(blank=True, max_length=50)),
                ('pais', models.CharField(blank=True, max_length=2)),
                ('grupos', models.ManyToManyField(to='practica_08.Grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('titulo', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('distribuidora', models.CharField(blank=True, max_length=30)),
                ('fecha_lanzamiento', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practica_08.Grupo')),
            ],
        ),
    ]
